repos:
  # - repo: https://github.com/psf/black  # Remove Black hook
  #   rev: 24.3.0
  #   hooks: [{id: black, args: ["--line-length", "100"]}]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    # Ensure ruff hook checks formatting and applies fixes
    hooks: [{id: ruff, args: ["--fix", "--show-fixes"]}, {id: ruff-format}]
    
  # Clean Python cache files
  - repo: local
    hooks:
      - id: clean-pycache
        name: Clean Python Cache
        entry: bash -c 'find . -type d -name "__pycache__" -exec rm -rf {} +; find . -type f -name "*.pyc" -delete'
        language: system
        pass_filenames: false
        always_run: true
