[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sentinelforge"
version = "0.0.1"
description = "AI‑powered threat‑intel aggregator"
authors = [{name = "Collin", email = "collinsorizu@gmail.com"}]
requires-python = ">=3.9"
