name: CI

on:
  push:
    branches: [main, ci/**, feat/**]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
          # Install ML-specific dependencies
          pip install -r requirements-ml.txt
      - name: Lint & format
        run: |
          ruff format . --check
          ruff check .
      - name: Clean Python cache
        run: |
          # Remove any __pycache__ directories and .pyc files to prevent import conflicts
          find . -type d -name '__pycache__' -exec rm -rf {} +
          find . -type f -name '*.pyc' -delete
      - name: Run tests
        run: make test-ci
