name: Pull Request Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
          
      - name: Run targeted tests
        run: |
          # Run only the ingestion API tests first to catch common failures quickly
          python -m pytest tests/test_ingestion/test_api.py -v
          
      - name: Run formatter and linter
        run: |
          ruff format . --check
          ruff check .
          
      - name: Run all tests
        run: |
          python -m pytest tests/ 